### ISSUE TITLE
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'

### ISSUE THREAD

**Issue by jardon** [canonical/mongodb-k8s-operator#108]
### Bug Description

The operator fails to deploy due to an incompatibility with openssl as discussed in this [bug](https://github.com/pyca/cryptography/issues/7959#issuecomment-1368711852)

### To Reproduce

tox -e integration

### Environment

```
integration installed: anyio==3.6.2,asttokens==2.2.1,attrs==22.2.0,backcall==0.2.0,bcrypt==4.0.1,black==22.12.0,CacheControl==0.12.11,cachetools==5.3.0,certifi==2022.12.7,cffi==1.15.1,charset-normalizer==3.0.1,cleo==2.0.1,click==8.1.3,codespell==2.2.2,coverage==7.1.0,crashtest==0.4.1,cryptography==39.0.0,decorator==5.1.1,distlib==0.3.6,dnspython==2.3.0,dulwich==0.20.50,exceptiongroup==1.1.0,executing==1.2.0,filelock==3.9.0,flake8==5.0.4,flake8-builtins==2.1.0,flake8-copyright==0.2.3,flake8-docstrings==1.7.0,google-auth==2.16.0,h11==0.14.0,html5lib==1.1,httpcore==0.16.3,httpx==0.23.3,idna==3.4,importlib-metadata==6.0.0,iniconfig==2.0.0,ipdb==0.13.11,ipython==8.8.0,isort==5.11.4,jaraco.classes==3.2.3,jedi==0.18.2,jeepney==0.8.0,Jinja2==3.1.2,jsonschema==4.17.3,juju==2.9.38.1,jujubundlelib==0.5.7,keyring==23.13.1,kubernetes==25.3.0,lightkube==0.12.0,lightkube-models==1.26.0.4,lockfile==0.12.2,macaroonbakery==1.3.1,MarkupSafe==2.1.2,matplotlib-inline==0.1.6,mccabe==0.7.0,more-itertools==9.0.0,msgpack==1.0.4,mypy-extensions==0.4.3,oauthlib==3.2.2,ops==2.0.0,packaging==23.0,paramiko==2.12.0,parso==0.8.3,pathspec==0.11.0,pep8-naming==0.13.3,pexpect==4.8.0,pickleshare==0.7.5,pkginfo==1.9.6,platformdirs==2.6.2,pluggy==1.0.0,poetry==1.3.2,poetry-core==1.4.0,poetry-plugin-export==1.3.0,prompt-toolkit==3.0.36,protobuf==3.20.3,ptyprocess==0.7.0,pure-eval==0.2.2,pyasn1==0.4.8,pyasn1-modules==0.2.8,pycodestyle==2.9.1,pycparser==2.21,pydocstyle==6.3.0,pyflakes==2.5.0,Pygments==2.14.0,pymacaroons==0.13.0,pymongo==4.3.3,PyNaCl==1.5.0,pyproject-flake8==5.0.4.post1,pyRFC3339==1.1,pyrsistent==0.19.3,pytest==7.2.1,pytest-asyncio==0.20.3,pytest-operator==0.23.0,python-dateutil==2.8.2,pytz==2022.7.1,PyYAML==6.0,rapidfuzz==2.13.7,requests==2.28.2,requests-oauthlib==1.3.1,requests-toolbelt==0.10.1,rfc3986==1.5.0,rsa==4.9,SecretStorage==3.3.3,shellingham==1.5.0.post1,six==1.16.0,sniffio==1.3.0,snowballstemmer==2.2.0,stack-data==0.6.2,tenacity==8.1.0,theblues==0.5.2,tomli==2.0.1,tomlkit==0.11.6,toposort==1.9,traitlets==5.8.1,trove-classifiers==2023.2.8,typing-inspect==0.8.0,typing_extensions==4.4.0,urllib3==1.26.14,virtualenv==20.19.0,wcwidth==0.2.6,webencodings==0.5.1,websocket-client==1.4.2,websockets==10.4,zipp==3.13.0
integration run-test-pre: PYTHONHASHSEED='54335413'
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/./src/charm.py", line 16, in <module>
    from charms.mongodb.v0.helpers import (
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/lib/charms/mongodb/v0/helpers.py", line 10, in <module>
    from charms.mongodb.v0.mongodb import MongoDBConfiguration, MongoDBConnection
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/lib/charms/mongodb/v0/mongodb.py", line 12, in <module>
    from pymongo import MongoClient
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/pymongo/__init__.py", line 92, in <module>
    from pymongo.mongo_client import MongoClient
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/pymongo/mongo_client.py", line 59, in <module>
    from pymongo import (
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/pymongo/uri_parser.py", line 23, in <module>
    from pymongo.client_options import _parse_ssl_options
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/pymongo/client_options.py", line 26, in <module>
    from pymongo.pool import PoolOptions
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/pymongo/pool.py", line 61, in <module>
    from pymongo.network import command, receive_message
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/pymongo/network.py", line 24, in <module>
    from pymongo import _csot, helpers, message, ssl_support
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/pymongo/ssl_support.py", line 22, in <module>
    import pymongo.pyopenssl_context as _ssl
  File "/var/lib/juju/agents/unit-mongodb-k8s-2/charm/venv/pymongo/pyopenssl_context.py", line 27, in <module>
    from OpenSSL import SSL as _SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 3279, in <module>
    _lib.OpenSSL_add_all_algorithms()
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
ERROR juju.worker.uniter.operation hook "db-storage-attached" (via hook dispatching script: dispatch) failed: exit status 1
```

**Comment by MiaAltieri** [comment]
Out of Date
