### ISSUE TITLE
Redeploying mongdb in the same model leads to authentication failure.

### ISSUE THREAD

**Issue by balbirthomas** [canonical/mongodb-k8s-operator#16]
## Steps to reproduce

1. Deploy mongodb charm
2. Use `juju remove-application` to remove the deployed mongodb-charm
3. Deploy mongodb charm again

This leads to an authentication failure error

```
unit-mongodb-k8s-0: 17:30:08 ERROR unit.mongodb-k8s/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/pool.py", line 1394, in _get_socket
    sock_info = self.sockets.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./src/charm.py", line 347, in <module>
    main(MongoDBCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/main.py", line 409, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/framework.py", line 278, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/framework.py", line 722, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/framework.py", line 767, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 105, in _on_config_changed
    self._on_update_status(event)
  File "./src/charm.py", line 160, in _on_update_status
    if not self.mongo.is_ready():
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/src/mongoserver.py", line 54, in is_ready
    client.server_info()
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/mongo_client.py", line 1994, in server_info
    return self.admin.command("buildinfo",
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/database.py", line 751, in command
    with self.__client._socket_for_reads(
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/mongo_client.py", line 1389, in _socket_for_reads
    with self._get_socket(server, session) as sock_info:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/mongo_client.py", line 1308, in _get_socket
    with server.get_socket(
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/pool.py", line 1331, in get_socket
    sock_info = self._get_socket(all_credentials)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/pool.py", line 1397, in _get_socket
    sock_info = self.connect(all_credentials)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/pool.py", line 1297, in connect
    sock_info.check_auth(all_credentials)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/pool.py", line 820, in check_auth
    self.authenticate(credentials)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/pool.py", line 837, in authenticate
    auth.authenticate(credentials, self)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/auth.py", line 672, in authenticate
    auth_func(credentials, sock_info)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/auth.py", line 588, in _authenticate_default
    return _authenticate_scram(credentials, sock_info, 'SCRAM-SHA-256')
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/auth.py", line 333, in _authenticate_scram
    res = sock_info.command(source, cmd)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/pool.py", line 710, in command
    return command(self, dbname, spec, secondary_ok,
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/network.py", line 158, in command
    helpers._check_command_response(
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/helpers.py", line 167, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1631118608, 2), 'signature': {'hash': b'C?n\xd4\xa0\xe1\xc4\x14\r\x04\x98;\x08w^Y\x02\xec\xc2\xc3', 'keyId': 7005600716479791108}}, 'operationTime': Timestamp(1631118608, 2)}
```

Courtsey : Nashwan Azhari for reporting this.

**Comment by balbirthomas** [comment]
This issue is happening because the shared volume mount retains the old shared key used by MongoDB units. An ideal solution would be to delete this key in the `StopEvent` but this does not seem to be a currently workable solution because a `ConnectionError` exception is raised when trying to access the `container.remove_path()` Pebble API in the stop event.
