### ISSUE TITLE
MongoDB <-> Grafana Agent integration doesn't work behind the proxy

### ISSUE THREAD

**Issue by Gmerold** [canonical/mongodb-k8s-operator#191]
## Steps to reproduce
1. Get an environment hidden behind proxy
2. Deploy `grafana-agent-k8s`
3. Deploy `mongodb-k8s` from `5/edge` channel
4. Integrate both applications: `juju integrate mongodb-k8s:logging grafana-agent-k8s:logging-provider`

## Expected behavior
Charms are integrated and go to `Active-Idle` state

## Actual behavior
```shell
Traceback (most recent call last):
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 1448, in connect
    super().connect()
  File "/usr/lib/python3.10/http/client.py", line 942, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/./src/charm.py", line 1218, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/framework.py", line 344, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/framework.py", line 833, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/framework.py", line 922, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/lib/charms/loki_k8s/v0/loki_push_api.py", line 1803, in _on_pebble_ready
    self._setup_promtail()
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/lib/charms/loki_k8s/v0/loki_push_api.py", line 2272, in _setup_promtail
    self._obtain_promtail(promtail_binaries[self._arch])
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/lib/charms/loki_k8s/v0/loki_push_api.py", line 1971, in _obtain_promtail
    self._download_and_push_promtail_to_workload(promtail_info)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/lib/charms/loki_k8s/v0/loki_push_api.py", line 2093, in _download_and_push_promtail_to_workload
    with request.urlopen(promtail_info["url"]) as r:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
```
After this exception, charm stays in  `Maintenance-Executing` state forever.

## Versions

Operating system: Ubuntu 22.04.2 LTS

Juju CLI: 3.1.5-genericlinux-amd64

Juju agent: 3.1.5

Charm revision: Channel `5/edge`, Revision 36

microk8s: MicroK8s v1.27.4 revision 5657

## Log output

Juju debug log: 

Relevant part presented above

**Comment by MiaAltieri** [comment]
Hi @Gmerold - Thanks for your message and your attention to detail here. IIRC mongodb cannot work via proxies by mongodb design. When the mongodb client makes a connection, the driver request list off all cluster members and recoonect to them directly. or fail if cannot access them

**Comment by MiaAltieri** [comment]
@Gmerold but sharding feature is coming (in VM sharding should be fully completed in 24.04, K8s 24.10). Sharding will support a special "proxy", i.e. mongos (mongos hides all the members). So that is something to look forward too :D
