### ISSUE TITLE
Mongodb-k8s goes in error when restoring from backup after reinstallation

### ISSUE THREAD

**Issue by ghislainbourgeois** [canonical/mongodb-k8s-operator#192]
## Steps to reproduce
1. juju add-model test
2. juju consume s3-integrator # deployed in another model
3. juju deploy mongodb-k8s --channel 5/edge
4. juju relate mongodb-k8s s3-integrator
5. juju run mongodb-k8s/0 create-backup
6. juju run mongodb-k8s/0 list-backups # wait until the backup is complete
7. juju remove-application mongodb-k8s
8. juju remove-storage mongodb/0
11. juju deploy mongodb-k8s --channel 5/edge
12. juju relate mongodb-k8s s3-integrator
13. juju run mongodb-k8s/0 list-backups # Confirm backup is there
14. juju run mongodb-k8s/0 restore backup-id=<backup_id>

## Expected behavior
Mongo finishes restoring properly and unit goes in active/idle status.

## Actual behavior
Mongo goes into an error state with a stack trace in the logs:

```
unit-mongodb-k8s-0: 19:56:40 INFO unit.mongodb-k8s/0.juju-log Deferring reconfigure: error=OperationFailure("Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1692921400, 1), 'signature': {'hash': b'\\xd6]\\xd4(\\xa4\\xe7M\\x0c=v\\xf1\\x08q\\x94\\x1b\\xeb\\x91\\xf0n\\xe8', 'keyId': 7271039350459072517}}, 'operationTime': Timestamp(1692921400, 1)}")
unit-mongodb-k8s-0: 19:56:40 ERROR unit.mongodb-k8s/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/./src/charm.py", line 1218, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/framework.py", line 344, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/framework.py", line 833, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/framework.py", line 922, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/./src/charm.py", line 479, in _on_update_status
    mongodb_status = build_unit_status(
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/lib/charms/mongodb/v0/helpers.py", line 168, in build_unit_status
    replset_status = mongo.get_replset_status()
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/lib/charms/mongodb/v0/mongodb.py", line 191, in get_replset_status
    rs_status = self.client.admin.command("replSetGetStatus")
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/_csot.py", line 105, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/database.py", line 805, in command
    with self.__client._socket_for_reads(read_preference, session) as (
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/mongo_client.py", line 1282, in _socket_from_server
    with self._get_socket(server, session) as sock_info:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/mongo_client.py", line 1217, in _get_socket
    with server.get_socket(handler=err_handler) as sock_info:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/pool.py", line 1407, in get_socket
    sock_info = self._get_socket(handler=handler)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/pool.py", line 1520, in _get_socket
    sock_info = self.connect(handler=handler)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/pool.py", line 1378, in connect
    sock_info.authenticate()
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/pool.py", line 870, in authenticate
    auth.authenticate(creds, self)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/auth.py", line 549, in authenticate
    auth_func(credentials, sock_info)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/auth.py", line 473, in _authenticate_default
    return _authenticate_scram(credentials, sock_info, "SCRAM-SHA-256")
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/auth.py", line 241, in _authenticate_scram
    res = sock_info.command(source, cmd)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/pool.py", line 767, in command
    return command(
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/network.py", line 166, in command
    helpers._check_command_response(
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/pymongo/helpers.py", line 181, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1692921400, 1), 'signature': {'hash': b'\xd6]\xd4(\xa4\xe7M\x0c=v\xf1\x08q\x94\x1b\xeb\x91\xf0n\xe8', 'keyId': 7271039350459072517}}, 'operationTime': Timestamp(1692921400, 1)}
```

## Versions

Operating system: Ubuntu 23.04

Juju CLI: 3.1.5-genericlinux-amd64

Juju agent: 3.1.5

Charm revision: 36

microk8s: MicroK8s v1.27.4 revision 5657

## Log output

Juju debug log:

**Comment by MiaAltieri** [comment]
Hi @ghislainbourgeois. Sorry for the delayed response I missed your message. From what you showed above in your example, I would expect this to fail with the error you showed.

The issue is that your new MongoDB deployment does not have the same password as the first deployment. When you restore it (in the way you have shown above) the new deployment restores the `admin` and `config` DBs as well (which is where the password is). If you do not set your new deployment to have the password from the first deployment, then when the deployment gets restored it gets the password for the first application, but the charm code still has the new password. And then the new deployment has a mismatch of passwords leading to the Auth error.

Therefore, before destroying the first mongodb deployment, get its password, and then with the new deployment reset the password. [Our documentation outlines this exact issue here](https://charmhub.io/mongodb-k8s/docs/h-migrate-cluster-via-restore?channel=5/edge)

In case that link isn't helpful I will send the correct steps here:
```
juju add-model test
juju consume s3-integrator # deployed in another model
juju deploy mongodb-k8s --channel 5/edge
juju relate mongodb-k8s s3-integrator
juju run mongodb-k8s/0 create-backup
juju run mongodb-k8s/0 list-backups # wait until the backup is complete

# new step
juju run mongodb-k8s/leader get-password 

juju remove-application mongodb-k8s
juju remove-storage mongodb/0


juju deploy mongodb-k8s --channel 5/edge

# new step
juju run mongodb-k8s/leader set-password password=<previous cluster password>

juju relate mongodb-k8s s3-integrator
juju run mongodb-k8s/0 list-backups # Confirm backup is there
juju run mongodb-k8s/0 restore backup-id=<backup_id>
```

We also test migration in [our integration tests](https://github.com/canonical/mongodb-k8s-operator/blob/8b9ebbee3f225ca98175c25781f1936dc4a62a7d/tests/integration/backup_tests/test_backups.py#L347) - maybe this can also be a useful reference for you :)

I hope this helps, if you're still having issues please let me know and I am happy to work closely with you on this :)
